name: Run Tests

on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install pytest
        uses: pip install pytest
      - name: Run tests
        run: pytest tests